DOMAIN = "naim_cdx"
DEFAULT_NAME = "Naim CDX"
SERVICE_SEND_COMMAND = "send_command"
CONF_BROADLINK = "broadlink_entity"
COMMANDS = {
    "play": "JgAsAB0eHB4fHDk8OR8bPRwfOD07OhwAC4UbIBsfHCA3PTkfGz0bHzk9OTwbAA0FAAAAAAAAAAAAAAAA",
    "pause": "JgAyAAZkHSEYIhkgOTs5IB45GyE5IBogGx8bAAujGx8bIRkgOT06HRw9Gx84IBshGiIYAA0FAAAAAAAA",
    "stop": "JgAoAB4gODw5PDofGj4aIDg+Gx84AAujGyA4PTg9OR8bPRsgOTwbHzkADQU=",
    "next": "JgAwABwfHB4cHzg9OR8dOzkgGx8bIBsgGgALoxwgGx4cIDk7Oh4cPDkfGx8dHxsfGwANBQAAAAAAAAAA",
    "previous": "JgAsABwgOjs5PTgfHjs4IBsfHB4dOxwAC4UdHzg8OT04Hxw6PB4bIBogGj4dAA0FAAAAAAAAAAAAAAAA",
    "repeat": "JgAsABsfOT05PDkfGx8cPBwfGyA4PRsAC4YbHzo8OD05HxsfHDwcHxsfOT0bAA0FAAAAAAAAAAAAAAAA",
    "disp": "JgAwAB0eHB8cHzk9Oh4dHhwfHTs5PRwfHQALdRsfHB8cHzk8Oh8cIBsbID05PRsgGwANBQAAAAAAAAAA",
    "one": "JgAwAB4fOTw5PTkfHCAbHxwfHCAbIBw8GwALdh0eOT05PTkfGyAcHxsgHCAbIBs9GgANBQAAAAAAAAAA",
    "two": "JgAwAB4dHB8bIDk9OR8bIBwfGyAbIBs9OQALkxwfHSAbHjk9OSAcIBogGx8cHxw8OAANBQAAAAAAAAAA",
    "three": "JgAwAB0eOT03PzkfHCAcIBseGyEcPBwgGwALdRweOT05PTchHCAbHx0gGyAbPBweHAANBQAAAAAAAAAA",
    "four": "JgAsAB4eNj85PDkgGyAdHhseHT03IRwAC5McHzk9Nz83IRwfHB8dHhw8OCMaAA0FAAAAAAAAAAAAAAAA",
    "five": "JgAwAB0fHB8cHjk9NyIcIBseHCAcOzk9HAALdR0eHSAbIDVANiEcHx0eHCAcPDk8HAANBQAAAAAAAAAA",
    "six": "JgAsABwgOD05PTkfHCAcHhwfHTscHzkAC5QbIDk8OT05IBsgGyAbHxw9HB85AA0FAAAAAAAAAAAAAAAA",
    "seven": "JgAwABwfOT05PDogGiAbIBwgGT4cHxwfGwALdh0eOjw5PTkfHB8dHhwfHDwcHxwfHAANBQAAAAAAAAAA",
    "eight": "JgAwAB0eHB8dHjk9OR8dHhwfHD05HxsgGwALlBwfHB8bHzo9OR8cHxsgGz05Hx0eHAANBQAAAAAAAAAA",
    "nine": "JgAsABsgOTw5PTkfHCAbIBs7Ox8cOx0AC3YcHzk9OTw6HxsgGyAcPDkfHD0bAA0FAAAAAAAAAAAAAAAA",
    "zero": "JgA0ABsgHB8bIDo7OSAbIBsgGyAcHxweHB8cAAuTHR4cHxwfOT05Hx0fGx8cHxwfGyAbIBwADQUAAAAA",
}
MANUFACTURER = ("Naim",)
MODEL = ("CDX",)
