send_command:
  name: Send Command
  description: Send command to Naim CDX
  target:
    entity:
      integration: naim_cdx
      domain: media_player
  fields:
    Command:
      name: Command
      description: "The Command to send to the device."
      required: true
      selector:
        select:
          multiple: false
          options:
            - play
            - pause
            - stop
            - next
            - previous
